version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-db-container
    restart: unless-stopped
    volumes:
      - ./sql/cloud_project.sql:/docker-entrypoint-initdb.d/cloud_project.sql
      - mysqldb:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "cloud"
      MYSQL_DATABASE: cloud_project
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnetwork
  node-server:
    container_name: node-server-container
    build:
      context: ./server/
    image: node-server-image
    volumes:
      - nodeapp:/usr/server
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: "cloud"
      DB_NAME: cloud_project
      SERVICE_TAGS: dev
      SERVICE_NAME: node-app-service
      SERVER_PORT: 8000
    depends_on:
      - mysqldb
    networks:
      - internalnetwork
volumes:
  mysqldb:
  nodeapp:
networks:
  internalnetwork:
    driver: bridge
